//------------------------------------------------------------------------------
// <auto-generated>
// This script was generated by XiheFramework
// Generation Time (UTC): 4/12/2025 10:23:03 PM
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConstant{
    public static class ResourceAddresses {
		public const string BallEntity_GeneralBall = "BallEntity_GeneralBall";
		public const string HoleEntity_BigHole = "HoleEntity_BigHole";
		public const string HoleEntity_SmallHole = "HoleEntity_SmallHole";
		public const string Scene_Game = "SceneAsset_Game";
		public const string Scene_Title = "SceneAsset_Title";
		public const string UIElement_StatsBar = "UIElementEntity_StatsBar";
		public const string UILayout_HudUIPage = "UILayoutEntity_HudUIPage";
		public const string UILayout_TitleUIPage = "UILayoutEntity_TitleUIPage";
    }
}